### PR TITLE
Add Api key param into requests

### PR DESCRIPTION
**Pull request by DKovalchuk**
Hi.

I just added a 'appid' param into requested url, because without it server response an error - 401 Unauthorized,

### CODE REVIEW

**Comment by TopperDEL** [comment]
Attention, you've included your personal API-key within this commit!

**Comment by DKovalchuk** [comment]
This is public API-key from documentation.

**Comment by TopperDEL** [comment]
Yeah, sorry - I realized that this is an official API-key and deleted my message. But it still reached you. I'm quiet now. :)

**Comment by Falco20019** [comment]
Please merge!

**Comment by DKovalchuk** [comment]
Thanks

**Pull request merged**
